task:
  world:
    world_model:
      coll_objs:
        sphere:
          sphere1:
            radius: 0.001
            position:
            - 10.2
            - -0.0
            - 0.4
        cube:
          table:
            dims:
            - 1.0
            - 1.0
            - 0.2
            pose:
            - 0.0
            - 0.0
            - -0.1
            - 0
            - 0
            - 0
            - 1.0
  name: FrankaReacher
  physics_engine: ${..physics_engine}
  env:
    numEnvs: 100
    envSpacing: 1.5
    episodeLength: 500
    enableDebugVis: false
    controlSpace: vel
    targetRandomizeMode: randomize_position
    clipObservations: 5.0
    startPositionNoise: 0.0
    startRotationNoise: 0.0
    aggregateMode: 3
    actionScale: 1.0
    dofVelocityScale: 0.1
    cost:
      goal_pose:
        weight:
        - 1.0
        - 1.0
        hinge_val: -1
        convergence_val:
        - 0.0
        - 0.0
      manipulability:
        weight: 10.0
        gaussian_params:
          'n': 0
          c: 0.0
          s: 0
          r: 10.0
        thresh: 0.03
    asset:
      assetRoot: ../../../content/assets
      assetFileNameFranka: urdf/franka_description/franka_panda_no_gripper.urdf
      assetFileNameTarget: urdf/mug/movable_mug.urdf
    enableCameraSensors: false
  sim:
    dt: 0.0166
    substeps: 1
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 12
      num_velocity_iterations: 1
      contact_offset: 0.005
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 1000.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 1048576
      num_subscenes: ${....num_subscenes}
      contact_collection: 0
  task:
    randomize: false
train:
  params:
    seed: ${...seed}
    algo:
      name: sac
    model:
      name: soft_actor_critic
    network:
      name: soft_actor_critic
      separate: true
      space:
        continuous: null
      mlp:
        units:
        - 256
        - 256
        activation: relu
        initializer:
          name: default
      log_std_bounds:
      - -5
      - 2
    load_checkpoint: false
    load_path: nn/Ant.pth
    config:
      name: ${resolve_default:FrankaReacher,${....experiment}}
      env_name: rlgpu
      normalize_input: true
      reward_shaper:
        scale_value: 1.0
      max_epochs: 50000
      num_steps_per_episode: 8
      save_best_after: 100
      save_frequency: 1000
      gamma: 0.99
      init_alpha: 1.0
      alpha_lr: 0.0003
      actor_lr: 0.0003
      critic_lr: 0.0003
      critic_tau: 0.005
      batch_size: 256
      learnable_temperature: true
      num_seed_steps: 5
      num_warmup_steps: 10
      replay_buffer_size: 1000000
      num_actors: ${....task.env.numEnvs}
mpc:
  use_cuda: true
  cuda_device_num: 0
  control_dt: 0.02
  run_open_loop: false
  control_space: acc
  env_control_space: ${resolve_default:'pos',${task.env.numEnvs}}
  float_dtype: float32
  state_filter_coeff:
    position: 0.1
    velocity: 0.0
    acceleration: 0.0
  n_dofs: 7
  model:
    urdf_path: urdf/franka_description/franka_panda_no_gripper.urdf
    learnable_rigid_body_config:
      learnable_links: []
    name: franka_panda
    max_acc: 5.0
    dt: 0.02
    dt_traj_params:
      base_dt: 0.02
      base_ratio: 0.5
      max_dt: 0.2
    ee_link_name: ee_link
    init_state:
    - 0.8
    - 0.3
    - 0.0
    - -1.57
    - 0.0
    - 1.86
    - 0.0
    link_names:
    - panda_link1
    - panda_link2
    - panda_link3
    - panda_link4
    - panda_link5
    - panda_link6
    - panda_hand
    vel_scale: 1.0
    collision_spheres: ../robot/franka.yml
    robot_collision_params:
      urdf: urdf/franka_description/franka_panda_no_gripper.urdf
      sample_points: 100
      link_objs:
      - panda_link1
      - panda_link2
      - panda_link3
      - panda_link4
      - panda_link5
      - panda_link6
      - panda_hand
      threshold: 0.35
      bounds:
      - - -0.5
        - -0.8
        - 0.0
      - - 0.5
        - 0.8
        - 1.0
      collision_spheres: ../robot/franka.yml
      self_collision_weights: robot_self/franka_self_sdf.pt
      dof: 7
    world_collision_params:
      model_path: scene_coll_nn/
      label_map:
        robot: 2
        ground: 0
      bounds:
      - - -1.0
        - -1.0
        - -0.2
      - - 1.0
        - 1.0
        - 1.0
      grid_resolution: 0.05
  cost:
    goal_pose:
      weight:
      - 100.0
      - 100.0
      hinge_val: -1
      convergence_val:
      - 0.0
      - 0.0
    zero_vel:
      weight: 0.0
      hinge_val: 0.2
      gaussian_params:
        'n': 0
        c: 0.2
        s: 0
        r: 1.0
    zero_acc:
      weight: 0.0
      hinge_val: -1.0
      gaussian_params:
        'n': 0
        c: 0.2
        s: 0
        r: 5.0
    collision:
      weight: 0.0
      gaussian_params:
        'n': 0
        c: 0.5
        s: 0
        r: 5.0
    primitive_collision:
      weight: 5000.0
      distance_threshold: 0.05
      gaussian_params:
        'n': 0
        c: 0.0
        s: 0
        r: 10.0
    robot_self_collision:
      weight: 5000.0
      distance_threshold: 0.05
      gaussian_params:
        'n': 0
        c: 0.0
        s: 0
        r: 10.0
    null_space:
      weight: 0.0
      gaussian_params:
        'n': 0
        c: 0.0
        s: 0
        r: 1.0
      vec_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5
      - 0.5
    manipulability:
      weight: 10.0
      gaussian_params:
        'n': 0
        c: 0.0
        s: 0
        r: 10.0
      thresh: 0.03
    joint_l2:
      weight: 0.0
      gaussian_params:
        'n': 0
        c: 0.2
        s: 0
        r: 5.0
    ee_vel:
      weight: 0.0
      vec_weight:
      - 1.0
      - 1.0
      - 1.0
      gaussian_params:
        'n': 0
        c: 0.0
        s: 0.0
        r: 5.0
    stop_cost:
      weight: 100.0
      max_nlimit: 1.5
      gaussian_params:
        'n': 0
        c: 0.0
        s: 0
        r: 1.0
    stop_cost_acc:
      weight: 0.0
      max_limit: 0.1
      gaussian_params:
        'n': 0
        c: 0.0
        s: 0
        r: 1.0
    voxel_collision:
      weight: 0.0
      gaussian_params:
        'n': 0
        c: 0.0
        s: 0
        r: 100.0
      distance_threshold: 0.05
      grid_resolution: 0.05
    smooth:
      weight: 0.0
      gaussian_params:
        'n': 0
        c: 0.2
        s: 0
        r: 10.0
      order: 1
    state_bound:
      weight: 1000.0
      gaussian_params:
        'n': 0
        c: 0.0
        s: 0
        r: 10.0
      bound_thresh: 0.05
    retract_state:
    - 0.0
    - 0.0
    - 0.0
    - -1.5
    - 0.0
    - 2.0
    - 0.0
    retract_weight:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  mppi:
    horizon: 30
    init_cov: 0.005
    gamma: 0.98
    n_iters: 1
    step_size_mean: 0.98
    step_size_cov: 0.7
    beta: 1.0
    alpha: 1
    num_particles: 500
    update_cov: false
    cov_type: diag_AxA
    kappa: 0.005
    null_act_frac: 0.01
    sample_mode: mean
    base_action: repeat
    squash_fn: clamp
    hotstart: true
    num_instances: ${resolve_default:4096,${task.env.numEnvs}}
    visual_traj: ee_pos_seq
    sample_params:
      type: halton
      fixed_samples: true
      sample_ratio:
        halton: 0.0
        halton-knot: 1.0
        random: 0.0
        random-knot: 0.0
      seed: 0
      filter_coeffs: null
      knot_scale: 4
  world: null
task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: ''
multi_gpu: false
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: isaacgymenvs
capture_video: false
capture_video_freq: 1464
capture_video_len: 100
force_render: true
headless: false
