##
## MIT License
##
## Copyright (c) 2020-2021 NVIDIA CORPORATION.
##
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.##

use_cuda: True
cuda_device_num: 0

control_dt: 0.02 #0.0166 #0.02
run_open_loop: False
control_space: 'acc'
env_control_space: 'joint_impedance'
float_dtype: 'float32'
state_filter_coeff: {'position':0.1, 'velocity':0.0, 'acceleration':0.0}
# cmd_filter_coeff: {'position':1.0, 'velocity':1.0, 'acceleration':0.0}
n_dofs: 7

rollout: ${task.rollout}
world: ${task.world}


mppi:
  num_instances     : 1
  horizon           : 30
  init_cov          : 0.05 #.5 #.5
  gamma             : 0.999
  n_iters           : 1
  step_size_mean    : 0.98
  step_size_cov     : 0.01 #0.7
  beta              : 0.1 #0.01 #1.0
  alpha             : 1
  num_particles     : 1000 #10000
  update_cov        : False
  cov_type          : 'diag_AxA' # 
  kappa             : 0.01 #0.005
  null_act_frac     : 0.001
  sample_mode       : 'mean'
  base_action       : 'repeat'
  squash_fn         : 'clamp'
  hotstart          : True
  visual_traj       : 'ee_pos_seq'
  sample_params:
    type: 'multiple'
    fixed_samples: True
    sample_ratio: {'halton':0.3, 'halton-knot':0.7, 'random':0.0, 'random-knot':0.0}
    seed: 0
    filter_coeffs: null #[0.3, 0.3, 0.4]
    knot_scale: 4
    bspline_degree: 3

