friction_cone_cost:
  cube1:
    m: 0.5
    com: [0.0, 0.0, 0.025]
    J: [[0.05, 0.0, 0.0], [0.0, 0.05, 0.0], [0.0, 0.0, 0.05]]
    mu: 0.5
    contact_points:
    - [0.025, 0.025, -0.025]
    - [-0.025, 0.025, -0.025]
    - [0.025, -0.025, -0.025]
    - [-0.025, -0.025, -0.025]
    friction_cost_weight: 0.2
    tangential_cost_weight: 0.0
  cube2: