joint_states_topic: 'joint_states'
joint_command_topic: 'franka_motion_control/joint_command'
ee_goal_topic: 'ee_goal'
robot_joint_names: ['panda_joint1', 'panda_joint2', 'panda_joint3', 'panda_joint4', 'panda_joint5', 'panda_joint6', 'panda_joint7']
world_description: '../../content/configs/gym/collision_wall_of_boxes.yml'
mpc_config: '../../content/configs/mpc/franka_reacher_real_robot.yml'
robot_coll_description: '../../content/configs/robot/franka_real_robot.yml'

fixed_frame: 'base_link'
ee_frame: 'ee_link'