
expert_data_path: './tmp_results/${task_name}/MPC/models/agent_buffer_0.pt'

policy:
  mlp_params:
    hidden_layers: [256, 256] 
    activation: torch.nn.ReLU 
    output_activation: null
    dropout_prob: 0.0 
    layer_norm: false
  init_std: 1.0
  min_std: 0.00001
  max_std: 10.0
  std_type: 'heteroscedastic'
  learn_logvar_bounds: false
  use_tanh: false

critic:
  mlp_params:
    hidden_layers: [256, 256] 
    activation: torch.nn.ReLU 
    output_activation: null
    dropout_prob: 0.0 
    layer_norm: false

agent:
  name: 'MPO'
  num_train_steps: 1000
  num_steps_per_env: 1
  num_update_steps: 1
  num_m_step_iterations: 5
  discount: 0.99
  train_batch_size: 256
  num_action_samples: 20
  q_transform: 'exponential'
  target_critic_update_freq: 250
  log_freq: 50
  checkpoint_freq: 500
  eval_freq: 100
  num_eval_episodes: 10
  epsilon: 0.1
  epsilon_kl: 0.00001
  init_eta: 1.0
  init_alpha: 0.0
  max_alpha: 10.0
  num_eta_iterations: 1
  policy_optimizer:
    __target__: torch.optim.Adam
    lr: 0.0003
  critic_optimizer:
    __target__: torch.optim.Adam
    lr: 0.0003
  eta_optimizer:
    __target__: torch.optim.Adam
    lr: 0.0003
  alpha_optimizer:
    __target__: torch.optim.Adam
    lr: 0.0003
  polyak_tau: 0.005

eval:
  checkpoint: './tmp_results/${task_name}/${train.agent.name}/models/agent_checkpoint_0.pt'
  num_eval_episodes: 10