
expert_data_path: 'simple_reaching_mpc'

policy:
  mlp_params:
    hidden_layers: [256, 256] 
    activation: torch.nn.ReLU 
    output_activation: null
    dropout_prob: 0.0 
    layer_norm: false
  init_std: 1.0
  min_std: 0.00001
  max_std: 10.0
  std_type: 'homoscedastic'
  learn_logvar_bounds: false
  use_tanh: false

agent:
  name: 'BP'
  num_train_steps: 1000
  train_batch_size: 256
  optimizer:
    __target__: torch.optim.Adam
    lr: 0.0001
  log_freq: 50
  checkpoint_freq: 500
  eval_freq: 100
  num_eval_episodes: 10
  # learn_deterministic_policy: false
  loss_type: nll
  num_action_samples: 32 #only used when learning std with mse loss
  fixed_alpha: 0.2

eval:
  checkpoint: './tmp_results/${task_name}/${train.agent.name}/models/agent_checkpoint_0.pt'
  num_eval_episodes: 10